import image from "../../../assets/Images/a.jpg";

export const patientData = [
  {
    id: 1,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: "08033966544",
    name: "John ",
    doctorAssigned: "Cheeh",
    disease: "Male",
    status: "Laspotech",
    img: image,
  },
  {
    id: 2,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: "08033966543",
    name: "Jane",
    doctorAssigned: "Widan",
    disease: "Female",
    status: "Laspotech",
    img: image,
  },
  {
    id: 3,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: "08022822453",
    name: "Mark",
    doctorAssigned: "White",
    disease: "Male",
    status: "Lapotech",
    img: image,
  },
  {
    id: 4,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: "08033977854",
    name: "Shawn",
    doctorAssigned: "Madison",
    disease: "Male",
    status: "laspotech",
    img: image,
  },
  {
    id: 5,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: "07044566789",
    name: "Polly ",
    doctorAssigned: "Paul",
    disease: "Male",
    status: "Laspotech",
    img: image,
  },
  {
    id: 6,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 25,
    name: "Mark Hall",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Asthma",
    status: "New Patient",
    img: image,
  },
  {
    id: 7,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 45,
    name: "Bill Gate",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Dental Care",
    status: "In Treatment",
    img: image,
  },
  {
    id: 8,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 35,
    name: "Ashely Cole",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Diabetes",
    status: "Recovered",
    img: image,
  },
  {
    id: 9,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 5,
    name: "Alicia Keys",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Covid-19 Suspect",
    status: "In Treatment",
    img: image,
  },
  {
    id: 10,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 52,
    name: "Ben White",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Diabetes",
    status: "New Patient",
    img: image,
  },
];
